### ISSUE TITLE
App crash on Heroku

### ISSUE THREAD

**Issue by davebanthorpe** [Runscope/requestbin#59]
Just created new HEroku account and deployed as per your instructions. Get an app crash in the logs as below:

D:\Git\requestbin>heroku logs
2018-05-01T16:00:02.713084+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
2018-05-01T16:00:02.713085+00:00 app[web.1]:     self.load_wsgi()
2018-05-01T16:00:02.713087+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2018-05-01T16:00:02.713088+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2018-05-01T16:00:02.713089+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-05-01T16:00:02.713090+00:00 app[web.1]:     self.callable = self.load()
2018-05-01T16:00:02.713092+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2018-05-01T16:00:02.713094+00:00 app[web.1]:     return self.load_wsgiapp()
2018-05-01T16:00:02.713095+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2018-05-01T16:00:02.713097+00:00 app[web.1]:     return util.import_app(self.app_uri)
2018-05-01T16:00:02.713099+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
2018-05-01T16:00:02.713100+00:00 app[web.1]:     __import__(module)
2018-05-01T16:00:02.713102+00:00 app[web.1]:   File "/app/requestbin/__init__.py", line 1, in <module>
2018-05-01T16:00:02.713104+00:00 app[web.1]:     import config
2018-05-01T16:00:02.713105+00:00 app[web.1]:   File "/app/requestbin/config.py", line 40, in <module>
2018-05-01T16:00:02.713107+00:00 app[web.1]:     url_parts = urlparse.urlparse(REDIS_URL)
2018-05-01T16:00:02.713109+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/urlparse.py", line 143, in urlparse
2018-05-01T16:00:02.713110+00:00 app[web.1]:     tuple = urlsplit(url, scheme, allow_fragments)
2018-05-01T16:00:02.713112+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/urlparse.py", line 182, in urlsplit
2018-05-01T16:00:02.713114+00:00 app[web.1]:     i = url.find(':')
2018-05-01T16:00:02.713115+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'find'
2018-05-01T16:00:02.713254+00:00 app[web.1]: [2018-05-01 16:00:02 +0000] [10] [INFO] Worker exiting (pid: 10)
2018-05-01T16:00:02.724967+00:00 app[web.1]: [2018-05-01 16:00:02 +0000] [4] [INFO] Shutting down: Master
2018-05-01T16:00:02.725163+00:00 app[web.1]: [2018-05-01 16:00:02 +0000] [4] [INFO] Reason: Worker failed to boot.
2018-05-01T16:00:05.467081+00:00 heroku[web.1]: Starting process with command `gunicorn --worker-class gevent --workers 2 --max-requests 1000 requestbin:app`
2018-05-01T16:00:07.932932+00:00 app[web.1]: [2018-05-01 16:00:07 +0000] [4] [INFO] Starting gunicorn 19.8.1
2018-05-01T16:00:07.933376+00:00 app[web.1]: [2018-05-01 16:00:07 +0000] [4] [INFO] Listening at: http://0.0.0.0:26758 (4)
2018-05-01T16:00:07.933548+00:00 app[web.1]: [2018-05-01 16:00:07 +0000] [4] [INFO] Using worker: gevent
2018-05-01T16:00:07.938691+00:00 app[web.1]: [2018-05-01 16:00:07 +0000] [9] [INFO] Booting worker with pid: 9
2018-05-01T16:00:07.952868+00:00 app[web.1]: [2018-05-01 16:00:07 +0000] [9] [ERROR] Exception in worker process
2018-05-01T16:00:07.952873+00:00 app[web.1]: Traceback (most recent call last):
2018-05-01T16:00:07.952875+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2018-05-01T16:00:07.952877+00:00 app[web.1]:     worker.init_process()
2018-05-01T16:00:07.952878+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
2018-05-01T16:00:07.952880+00:00 app[web.1]:     super(GeventWorker, self).init_process()
2018-05-01T16:00:07.952882+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
2018-05-01T16:00:07.952883+00:00 app[web.1]:     self.load_wsgi()
2018-05-01T16:00:07.952885+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2018-05-01T16:00:07.952887+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2018-05-01T16:00:07.952889+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-05-01T16:00:07.952891+00:00 app[web.1]:     self.callable = self.load()
2018-05-01T16:00:07.952892+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2018-05-01T16:00:07.952894+00:00 app[web.1]:     return self.load_wsgiapp()
2018-05-01T16:00:07.952896+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2018-05-01T16:00:07.952897+00:00 app[web.1]:     return util.import_app(self.app_uri)
2018-05-01T16:00:07.952899+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
2018-05-01T16:00:07.952900+00:00 app[web.1]:     __import__(module)
2018-05-01T16:00:07.952903+00:00 app[web.1]:   File "/app/requestbin/__init__.py", line 1, in <module>
2018-05-01T16:00:07.952904+00:00 app[web.1]:     import config
2018-05-01T16:00:07.952906+00:00 app[web.1]:   File "/app/requestbin/config.py", line 40, in <module>
2018-05-01T16:00:07.952907+00:00 app[web.1]:     url_parts = urlparse.urlparse(REDIS_URL)
2018-05-01T16:00:07.952909+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/urlparse.py", line 143, in urlparse
2018-05-01T16:00:07.952911+00:00 app[web.1]:     tuple = urlsplit(url, scheme, allow_fragments)
2018-05-01T16:00:07.952912+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/urlparse.py", line 182, in urlsplit
2018-05-01T16:00:07.952914+00:00 app[web.1]:     i = url.find(':')
2018-05-01T16:00:07.952916+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'find'
2018-05-01T16:00:07.953038+00:00 app[web.1]: [2018-05-01 16:00:07 +0000] [9] [INFO] Worker exiting (pid: 9)
2018-05-01T16:00:07.955710+00:00 app[web.1]: [2018-05-01 16:00:07 +0000] [10] [INFO] Booting worker with pid: 10
2018-05-01T16:00:07.971412+00:00 app[web.1]: [2018-05-01 16:00:07 +0000] [10] [ERROR] Exception in worker process
2018-05-01T16:00:07.971416+00:00 app[web.1]: Traceback (most recent call last):
2018-05-01T16:00:07.971418+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2018-05-01T16:00:07.971420+00:00 app[web.1]:     worker.init_process()
2018-05-01T16:00:07.971421+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
2018-05-01T16:00:07.971423+00:00 app[web.1]:     super(GeventWorker, self).init_process()
2018-05-01T16:00:07.971424+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
2018-05-01T16:00:07.971426+00:00 app[web.1]:     self.load_wsgi()
2018-05-01T16:00:07.971427+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2018-05-01T16:00:07.971429+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2018-05-01T16:00:07.971431+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-05-01T16:00:07.971432+00:00 app[web.1]:     self.callable = self.load()
2018-05-01T16:00:07.971434+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2018-05-01T16:00:07.971436+00:00 app[web.1]:     return self.load_wsgiapp()
2018-05-01T16:00:07.971437+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2018-05-01T16:00:07.971438+00:00 app[web.1]:     return util.import_app(self.app_uri)
2018-05-01T16:00:07.971440+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
2018-05-01T16:00:07.971441+00:00 app[web.1]:     __import__(module)
2018-05-01T16:00:07.971443+00:00 app[web.1]:   File "/app/requestbin/__init__.py", line 1, in <module>
2018-05-01T16:00:07.971445+00:00 app[web.1]:     import config
2018-05-01T16:00:07.971446+00:00 app[web.1]:   File "/app/requestbin/config.py", line 40, in <module>
2018-05-01T16:00:07.971448+00:00 app[web.1]:     url_parts = urlparse.urlparse(REDIS_URL)
2018-05-01T16:00:07.971450+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/urlparse.py", line 143, in urlparse
2018-05-01T16:00:07.971452+00:00 app[web.1]:     tuple = urlsplit(url, scheme, allow_fragments)
2018-05-01T16:00:07.971453+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/urlparse.py", line 182, in urlsplit
2018-05-01T16:00:07.971455+00:00 app[web.1]:     i = url.find(':')
2018-05-01T16:00:07.971457+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'find'
2018-05-01T16:00:07.971690+00:00 app[web.1]: [2018-05-01 16:00:07 +0000] [10] [INFO] Worker exiting (pid: 10)
2018-05-01T16:00:07.983428+00:00 app[web.1]: [2018-05-01 16:00:07 +0000] [4] [INFO] Shutting down: Master
2018-05-01T16:00:07.983550+00:00 app[web.1]: [2018-05-01 16:00:07 +0000] [4] [INFO] Reason: Worker failed to boot.
2018-05-01T16:00:08.042591+00:00 heroku[web.1]: Process exited with status 3
2018-05-01T16:00:08.062123+00:00 heroku[web.1]: State changed from starting to crashed
2018-05-01T16:00:40.082768+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=intense-brushlands-XXXXX.herokuapp.com request_id=ce3ab664-d2a2-46b7-b1ea-3fefac5a624d fwd="86.185.60.80" dyno= connect= service= status=503 bytes= protocol=https
2018-05-01T16:00:41.163243+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=intense-brushlands-XXXXX.herokuapp.com request_id=fdab69a1-1ae5-4111-b057-c2ac136df670 fwd="86.185.60.80" dyno= connect= service= status=503 bytes= protocol=https
2018-05-01T16:01:21.759671+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=intense-brushlands-XXXXX.herokuapp.com request_id=7167c06b-d3a4-45c1-bad7-8ef5a7a750c4 fwd="86.185.60.80" dyno= connect= service= status=503 bytes= protocol=https
2018-05-01T16:01:22.009514+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=intense-brushlands-XXXXX.herokuapp.com request_id=33ec7d21-ef3a-4c14-af37-a63f0fcf659f fwd="86.185.60.80" dyno= connect= service= status=503 bytes= protocol=https
2018-05-01T16:01:22.851008+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=intense-brushlands-XXXXX.herokuapp.com request_id=1ea42d2a-724b-4aad-a3f7-dcb4f8084f4f fwd="86.185.60.80" dyno= connect= service= status=503 bytes= protocol=https
2018-05-01T16:01:23.106167+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=intense-brushlands-XXXXX.herokuapp.com request_id=fdde004f-8b67-47c1-9291-d13295d73c26 fwd="86.185.60.80" dyno= connect= service= status=503 bytes= protocol=https
2018-05-01T16:01:50.130251+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/requestbin" host=intense-brushlands-XXXXX.herokuapp.com request_id=e0cf51ec-1c94-4b5a-8746-2b1c3ab89dd3 fwd="86.185.60.80" dyno= connect= service= status=503 bytes= protocol=https
2018-05-01T16:01:50.820311+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=intense-brushlands-XXXXX.herokuapp.com request_id=c9c5cfcd-8dd6-4900-8efa-133e2baf7300 fwd="86.185.60.80" dyno= connect= service= status=503 bytes= protocol=https
2018-05-01T16:01:57.375931+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=intense-brushlands-XXXXX.herokuapp.com request_id=37921802-6bbd-4e1f-af2d-da70d253b85b fwd="86.185.60.80" dyno= connect= service= status=503 bytes= protocol=https
2018-05-01T16:01:57.621446+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=intense-brushlands-XXXXX.herokuapp.com request_id=83c4600d-fbd0-4add-a03e-c33233770e2f fwd="86.185.60.80" dyno= connect= service= status=503 bytes= protocol=https

**Comment by davebanthorpe** [comment]
all fixed - needed to pay for the redis cache
